language: r
cache:
  - packages
  - apt: true

os: linux
dist: bionic
sudo: required

addons:
  apt:
    update: true
    packages:
      - libquantlib0-dev
      - libboost-dev
      - libboost-test-dev

after_success:
  - Rscript -e 'covr::codecov()'
